name = "HilbertPolyaBostConnes"
defaultTargets = ["HilbertPolyaBostConnes"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "5e932f97dd25535344f80f9dd8da3aab83df0fe6"

[[require]]
name = "TtBostConnes"
git = "https://github.com/localparty/tt-bost-connes-lean"
rev = "d4bb8949e37f5e4b9769331294e8fb6e07b6de87"

[[lean_lib]]
name = "HilbertPolyaBostConnes"
